from django.conf.urls import patterns, url
# from zap_apps.zap_admin import views
from zap_apps.zap_admin.views import *

urlpatterns = [
    url(r'^$', home),
    url(r'^user/(?P<p_id>[0-9]*)?/$', user_profile),
    url(r'^user/search/(?P<query_string>.+)$', user_search),
    url(r'^product/search/(?P<query_string>.+)$', product_search),
    url(r'^get_upload_details/$', get_upload_details),
    url(r'^get_productsToApprove/(?P<page>[0-9]*)/$', get_productsToApprove),
    url(r'^get_approvedProducts/(?P<page>[0-9]*)/$', get_approvedProducts),
    url(r'^get_disapprovedProducts/(?P<page>[0-9]*)/$', get_DisapprovedProducts),
    url(r'^product/(?P<p_id>[0-9]*)(/?)$', Product),
    url(r'^approve/(?P<p_id>[0-9]*)(/?)$', Approve),
    url(r'^reject/(?P<p_id>[0-9]*)(/?)$', Reject),
    url(r'^get_userDetais/$', get_userDetails),
    url(r'^orders/$', get_orders),
    url(r'^admin_orders/$', get_admin_orders),
    url(r'^get_notifyUsers/$', NotifyUsers),
    url(r'^returns/$', GetReturns),
    url(r'^upload/$', UploadProduct),
    url(r'^upload/image$', UploadImage),
    url(r'^get_users/$', GetUsers),
    url(r'^logistics_evaluation/$', GetLogisticsEval),
    url(r'^address/(?P<u_id>[0-9]*)(/?)$', GetAddress),
    url(r'^get_products_count/$', GetProductsCount),
    url(r'^get_users_details/$', GetUsersDetails),
    url(r'^get_order_details/$', GetOrdersDetails),
    url(r'^get_action_datas/$', GetActionDatas),
    url(r'^logistics_rejection/$', LogisticsRejection),
    url(r'^load_users/$', LoadUsers),
    url(r'^load_user_addresses/$', LoadUserAddressess),
    url(r'^update_product/$', UpdateProduct),
    url(r'^edit/(?P<p_id>[0-9]*)/(?P<action>.+)/$', editProduct),
    url(r'^edit_product/$', EditProduct),
    url(r'^accountnumber/(?P<pk>[0-9]+)(/?)$', UserAccountNumberByAdmin),
    url(r'^load_zapexc_accounts/$', load_zapexc_accounts),
    url(r'^before_process/$', before_process),
    url(r'^in_process/$', in_process),
    url(r'^done_process/$', done_process),
    url(r'^verify_pickedup/$', verify_pickedup),
    url(r'^trigger_return/$', trigger_return),
    url(r'^return_trigger/$', return_trigger),
    url(r'^export/$', export_view),
    url(r'^export/website/$', export_website_view),
    url(r'^export/order(/?)$', export_order_view),
    url(r'^export/cart$', export_cart),
    url(r'^export/order/(?P<confirmed>confirmed)(/?)$', export_order_view),
    url(r'^export/user/$', export_user),
    url(r'^export/user_credit/$', export_user_credit_view),
    url(r'^export/products/$', export_product_view),
    url(r'^export/user_preference/$', export_user_preference_view),
    url(r'^export/sellers/$', export_seller_details),
    url(r'^export/amazon/$', export_amazon),
    url(r'^export/(?P<item>.*)/$', export_item_count),
    url(r'^send_notification/$', marketing_notification),
    url(r'^seller_buyer_account/$', seller_buyer_account),
    url(r'^get_brand_products/$', get_brand_products),
    url(r'^track_order/$', track_logistics_status),
]
